language: node_js
node_js:
  - '6'
install:
  - yarn
script:
  - echo 'no tests'
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: dist
  domain: service-manual-prototype.surge.sh
  on:
    branch: master
